### PR TITLE
Scala 2.12.8

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by stanislav-chetvertkov** [comment]
@blast-hardcheese Is the compiler bug issue https://github.com/twilio/guardrail/commit/cc20e726a89d17b1779a220114f6a05c3c9de2a4 still relevant?

**Comment by blast-hardcheese** [comment]
Yes, I'll check to see if the issue is fixed in this new version

**Comment by blast-hardcheese** [comment]
Ah, yes, even 2.12.8 snapshot had this issue, and there's been no movement on https://github.com/scala/bug/issues/11243

**Comment by tomasherman** [comment]
any reason this isn't merged? it would help with metals integration ;)

**Comment by tomasherman** [comment]
is the bug a big deal? It's a bit sad this can't be merged as it blocks `metals` from working properly :)

**Comment by blast-hardcheese** [comment]
This bug was causing errors in completely unrelated code; it took an hour to resolve a relatively simple bug because the error was at the end of a very large function. This is very similar to

```scala
case Foo(a,b,c) =>
  def foo = ???
  foo
```
being completely fine for months, then something small changes and 
```scala
def foo = ???

case Foo(a,b,c) =>
  foo
```
is required to get it to compile again (the current assumption is due to some unsurfaced path dependence on return types)

The motivation of getting metals working with guardrail is definitely understandable. If I can get a repro working in scalac directly, I may be able to bisect to figure out what caused the bug and fix it.

Linking to https://github.com/scala/bug/issues/11243 for visibility

**Pull request merged**
