### PR TITLE
Polymorphism

### PR DESCRIPTION
**Pull request by stanislav-chetvertkov**
trying to add support for #43

### CODE REVIEW

**Comment by metasim** [comment]
@stanislav-chetvertkov I'm interested in this fix... is it still pending?

**Comment by stanislav-chetvertkov** [comment]
@metasim me to... still working on it though only occasionally, It turned out more complex than I expected and my initial approach didn't work...

**Comment by dpblh** [comment]
Looking forward to these changes :)

**Comment by dpblh** [comment]
I don't know if there is a notify of pull request
https://github.com/twilio/guardrail/pull/98

**Comment by stanislav-chetvertkov** [comment]
@blast-hardcheese, if this approach makes sense I can rebase on top of the latest master and add some tests, this branch is far behind already...

**Comment by dpblh** [comment]
@stanislav-chetvertkov 
Encoder & Decoder was fixed. It looks a few ugly, but it really works on my gigantic `swagger.yaml`

**Comment by blast-hardcheese** [comment]
Closing this in favor of #104

**Pull request closed without merging**
