### PR TITLE
enable sbt-ci-release plugin

### PR DESCRIPTION
**Pull request by sullis**
- add `sbt-ci-release` plugin to plugins.sbt
- GitHub Actions will invoke "sbt ci-release"
- enable Release Drafter GitHub Action

For more details, see: 
https://github.com/olafurpg/sbt-ci-release

```
[sbt-ci-release] is an sbt plugin to help automate releases to Sonatype and Maven Central from GitHub Actions.

- git tag pushes are published as regular releases to Maven Central
- merge into master commits are published as -SNAPSHOT with a unique version number for every commit

```

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

Screen Shot 2020-08-29 at 12 18 36 PM

Ólafur Páll Geirsson recommends GitHub Actions over TravisCI:

https://github.com/olafurpg/sbt-ci-release/pull/152

### CODE REVIEW

**Comment by sullis** [comment]
fyi:  [sbt-ci-release] is used in the ScalaMeta project
https://github.com/scalameta/scalameta/blob/master/project/plugins.sbt

**Comment by blast-hardcheese** [comment]
@sullis Where do we stand on this, now that Actions is GA?

**Comment by sullis** [comment]
I hope we can find a way to test this.  (I can't test it --- I don't have access to Guardrail secrets)

**Comment by sullis** [comment]
@sullis can you take a look at this?

**Comment by sullis** [comment]
BTW, there is another way to use `sbt-ci-release` with GitHub Actions.

See:  https://github.com/softwaremill/tapir/blob/master/.github/workflows/ci.yml

**Review by blast-hardcheese — APPROVED** [review]
Thank you @sullis! It took a bit to circle back, but I believe all the kinks have been worked out.

One caveat of this is that we'll no longer be publishing to bintray. The vast majority of users seem to be downloading via Maven Central, presumably due to the fact that we initially _only_ published to bintray.

I'll include a note to this effect in the release notes, but anyone who can't utilize Maven Central please feel free to comment here, we'll figure something out.

**Pull request merged**
