### PR TITLE
Update Circe v0.10.x

### PR DESCRIPTION
**Pull request by sjbog**

### CODE REVIEW

**Comment by blast-hardcheese** [comment]
Partial duplicate of #132, though if you apply the change suggested in https://github.com/twilio/guardrail/pull/132#discussion_r231950249 I'd gladly merge and release

**Comment by blast-hardcheese** [comment]
as this has been requested before (#114), I think it's important to get this out instead of waiting for timezone issues to be resolved

**Comment by sjbog** [comment]
Tried to do implicit mirroring
```
def mirrorCirce[T]: T = {
    import io.circe.java8.time._
    implicitly[T]
}

implicit val decodeInstant: Decoder[Instant]  = mirrorCirce[Decoder[Instant]].or(decodeLong.map(Instant.ofEpochMilli))
```
but complains that implicitly can't work with generics
```
definitions/package.scala:11: could not find implicit value for parameter e: T
[error]     implicitly[T]
[error]               ^
```

----
Were there any issues with direct import?
```
import io.circe.java8.time._

implicit val decodeInstant: Decoder[Instant] = implicitly[Decoder[Instant]].or(decodeLong.map(Instant.ofEpochMilli))
```

**Comment by blast-hardcheese** [comment]
Is implicit resolution not a concern here?
```scala
scala> trait Foo[A]
defined trait Foo

scala> implicit def getFoo: Foo[Long] = ???
getFoo: Foo[Long]

scala> implicit val overrideFoo: Foo[Long] = implicitly[Foo[Long]]
<console>:15: error: ambiguous implicit values:
 both method getFoo of type => Foo[Long]
 and value overrideFoo of type => Foo[Long]
 match expected type Foo[Long]
       implicit val overrideFoo: Foo[Long] = implicitly[Foo[Long]]
                                                       ^
```

or from another package:
```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

package object bleh { trait Bar[A] ; implicit def defaultLongBar: Bar[Long] = ??? }

// Exiting paste mode, now interpreting.


scala> import bleh._
import bleh._

scala> implicit val overrideBar: Bar[Long] = implicitly[Bar[Long]]
<console>:17: error: ambiguous implicit values:
 both method defaultLongBar in package bleh of type => bleh.package.Bar[Long]
 and value overrideBar of type => bleh.Bar[Long]
 match expected type bleh.Bar[Long]
       implicit val overrideBar: Bar[Long] = implicitly[Bar[Long]]
                                                       ^
```

**Comment by blast-hardcheese** [comment]
gotta be really careful here:
```scala
scala> import io.circe.java8.time._
import io.circe.java8.time._

scala> import io.circe._
import io.circe._

scala> import java.time.Instant
import java.time.Instant

scala> implicit val decodeInstant: Decoder[Instant] = implicitly[Decoder[Instant]]
decodeInstant: io.circe.Decoder[java.time.Instant] = null
```

**Comment by blast-hardcheese** [comment]
oh, this doesn't even work with the local implicit resolution

**Pull request merged**
