### PR TITLE
improve parameter error messages

### PR DESCRIPTION
**Pull request by sullis**
Include the parameter name in the  error messages

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by blast-hardcheese** [comment]
What was the previous error message, `...parameter[2]` or something?

**Comment by sullis** [comment]
The previous message was

`Parameter has no schema`

This PR adds the parameter name to the message.

**Comment by blast-hardcheese** [comment]
This uses the `raiseErrorIfEmpty` mechanism though, it should provide a path to the element that failed validation immediately after the error message. Would you mind confirming whether it's there or not?

**Comment by sullis** [comment]
Without this PR:

```
Error: Parameter has no schema type (.paths./v2/Apples/Oranges.operations.POST.requestBody[0].content.application/json.schema.type)
```

With this PR:

```
Error: Parameter chef_environments has no schema type (.paths./v2/Apples/Oranges.operations.POST.requestBody[0].content.application/json.schema.type)
```

**Comment by blast-hardcheese** [comment]
Ah, that is better.
We should still give a useful message even if the `name` parameter is `null` though, other than that :+1: from me.

**Pull request merged**
