### PR TITLE
Update Scalameta. Fixes #429

### LINKED ISSUE #429: Enum values are not enclosed in backticks, preventing correct code generation for certain patterns
Exemple:
```json
	 "returned_anwsers_count": {
          "type": "string",
          "enum": [
            "10"
          ]
        }
```
results in:

```scala
  object ReturnedAnwsersCount {
    object members { case object 10 extends ReturnedAnwsersCount("10") }
    val 10: ReturnedAnwsersCount = members.10
    val values = Vector(10)
```

Which is not valid Scala code

It may be

```scala
  object ReturnedAnwsersCount {
    object members { case object `10` extends ReturnedAnwsersCount("10") }
    val `10`: ReturnedAnwsersCount = members.`10`
    val values = Vector(10)
```

### PR DESCRIPTION
**Pull request by sbrunk**
**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by blast-hardcheese** [comment]
To avoid regression, would you mind adding a small specfile that tests this functionality?

**Comment by sbrunk** [comment]
I actually have a test ready but it passes even with the old version for some reason when comparing the structures (generating files shows the difference though). I'll add the test nevertheless. Perhaps you have an idea what needs to be compared to show the behavior.

**Comment by blast-hardcheese** [comment]
my thought would be that `Lit.Int(10)` should be used anywhere, whereas `Term.Name("10")` should always fail. I presume the scala.meta upgrade would fix this by escaping the `Term.Name("10")`

**Comment by sbrunk** [comment]
```scala
@ import $ivy.`org.scalameta::scalameta:4.1.0`, scala.meta._
@ Term.Name("10").syntax
res1: String = "10"
```

```scala
@ import $ivy.`org.scalameta::scalameta:4.2.4`, scala.meta._
@ Term.Name("10").syntax
res1: String = "`10`"
@ Defn.Object(List(), Term.Name("10"), Template(List(), List(), Self(Name(""), None), List())).syntax
res2: String = "object `10`"
```

So perhaps we could simply add
```scala
Term.Name("10").syntax shouldBe "`10`"
```
as additional test condition.

**Comment by blast-hardcheese** [comment]
@sbrunk I'm onboard with that, though still interested in why https://github.com/twilio/guardrail/pull/430#issuecomment-548574779 is the case

**Comment by sbrunk** [comment]
> my thought would be that `Lit.Int(10)` should be used anywhere, whereas `Term.Name("10")` should always fail. I presume the scala.meta upgrade would fix this by escaping the `Term.Name("10")`

I'm not sure I understand. Why should `Lit.Int(10)` be used anywhere?

**Comment by blast-hardcheese** [comment]
@sbrunk This is excellent, thank you for your investigation! I'll try to get a bugfix release out with this at some point this weekend.

cc @nb-ceffa, @tomasherman

**Comment by tomasherman** [comment]
Thank you!

**Comment by sbrunk** [comment]
If only every bugfix was that simple 😀

**Pull request merged**
