### PR TITLE
Add @javax.annotations.Generated to Java generators

### PR DESCRIPTION
**Pull request by kpavlov**
**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by kelnos** [comment]
Do IDEs/linters/other tools do anything useful with this?  I like the idea of doing this for completeness, but since it requires users to add yet another dependency, I'd rather not unless there's a clear user-facing benefit.

**Comment by andrewryno** [comment]
Most code coverage analyzers will ignore anything with that annotation. SonarQube for example won't factor in any generated code for coverage metrics.

**Comment by kelnos** [comment]
Ah, that's really useful then.

**Review by kelnos — CHANGES_REQUESTED** [review]
Looks good, but please add a note to MIGRATING.md about the new required dependency.

**Comment by kpavlov** [comment]
> Most code coverage analyzers will ignore anything with that annotation. SonarQube for example won't factor in any generated code for coverage metrics.
That was exactly the reason of this PR. Now we have to manually exclude Guardrail-generated code to jacoco excludes.

_javax.annotations:javax.annotation-api_ dependency is required for JDK9+ only.

BTW, the Guardrail's missing feature is a target JVM version flag or understanding "maven.compiler.source" property.
If the flag was be present then no dependency would be needed. Depending on the java version either `@javax.annotations.Generated` (<=JDK8) or `@javax.annotation.processing.Generated` annotations should be used.

**Comment by kelnos** [comment]
> BTW, the Guardrail's missing feature is a target JVM version flag or understanding "maven.compiler.source" property.

It's possible to handle this using guardrail's module system, but I don't think it's worth it just for <=8, especially since it'll still work with 8 and below by adding the extra dependency.

**Comment by kelnos** [comment]
I'm a little confused, though.  You're using `@javax.annotations.Generated`, but that will only work on JDK 8 and below?  And for JDK 9 and above you need to use `@javax.annotation.processing.Generated`?  If so, that's a blocker; we can't stop supporting 9 and above.

**Comment by kpavlov** [comment]
It's not a blocker. For 9 and above customers have to add extra dependency as the annotation has moved. For 8 and below - no need for javax.annotations api dependency.

**Comment by kpavlov** [comment]
> It's possible to handle this using guardrail's module system, but I don't think it's worth it just for <=8, especially since it'll still work with 8 and below by adding the extra dependency.

No, we need a dependency for 9+

**Comment by head-thrash** [comment]
i guess the idea here is to use java8 annotation. _if_ you're building for jdk >8 you have to import a lib which has old 1.8 annotations, and yes, in new java they moved in to separate namespace

i think this is a stuff that we have to be diligent about since 
a) odd library from old jdk8 makes guardrail jdk8 aware/specific.
b) jdk8 lib may interfere with some existing code that may use jdk9+ namespace

**Review by kelnos — APPROVED** [review]
Apologies for not getting back to this.  Fortunately this is going to be a work-on-guardrail week for me.  Thank you for clarifying when the new dep is needed, that seems fine to me.  And a big thanks also for updating (and writing new) documentation!

**Comment by kelnos** [comment]
Stupid merge conflicts...

**Pull request merged**
