### PR TITLE
Add unexpected status handling in http4s client

### PR DESCRIPTION
**Pull request by cponomaryov**

### CODE REVIEW

**Comment by cponomaryov** [comment]
`fetch` is implemented as follows:
`def fetch[A](req: Request[F])(f: Response[F] => F[A]): F[A] = run(req).use(f)`
Here is a doc for method `use`:
```
/**
   * Allocates a resource and supplies it to the given function.  The
   * resource is released as soon as the resulting `F[B]` is
   * completed, whether normally or as a raised error.
   *
   * @param f the function to apply to the allocated resource
   * @return the result of applying [F] to
   */
```

**Comment by cponomaryov** [comment]
@blast-hardcheese could you please merge if you are ok with this solution?

**Comment by blast-hardcheese** [comment]
Thanks for the info about `fetch`!

**Comment by blast-hardcheese** [comment]
@cponomaryov Thank you for your patience without a full release; #133 combined with the US Holiday has set me back a bit. I haven't forgotten about it.

**Comment by cponomaryov** [comment]
@blast-hardcheese no problem, take your time

**Comment by blast-hardcheese** [comment]
@cponomaryov OK, 0.41.2 has been released, waiting for the maven plugin to sync now

**Pull request merged**
